name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
            uses: actions/checkout@v4

        - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: 3.12

        - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pytest black flake8

        - name: Run code formatting check (black)
            run: |
                black --check .
        - name: Run linting (flake8)
            run: |
                flake8 .
        - name: Run tests
            run: |
                pytest
